/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package E_Hospital_Management;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author sharath
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUserId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        txtType = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Login");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setText("User ID");

        txtUserId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserIdActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel3.setText("Password");

        jButton1.setBackground(new java.awt.Color(0, 153, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Login\n");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 153, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Cancel");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 153, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Patient Registeration");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Type");

        txtType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None ", "Staff ", "Doctor", "Patient", "Admin" }));

        jLabel5.setText("___________________________________________________________________________________________");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("For patient's Registration click below");
        jLabel6.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(42, 42, 42)
                                .addComponent(jButton4)
                                .addGap(37, 37, 37))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel4))
                                        .addGap(42, 42, 42)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtUserId, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                                    .addComponent(txtPassword)
                                    .addComponent(txtType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jButton2)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtUserId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserIdActionPerformed
Connection con;
PreparedStatement pst;
PreparedStatement pst2;
PreparedStatement pst3;
ResultSet rs;
ResultSet rs2;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        
        int uid=Integer.parseInt(txtUserId.getText());
        String password=txtPassword.getText();
        
        if(txtUserId.getText().isEmpty() && password.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Enter all the credentials");
        }
        else if(txtType.getSelectedIndex()==0)
        {
            JOptionPane.showMessageDialog(this, "Enter the type pf user");
        }
        else
        {
            try {
                Class.forName("com.mysql.jdbc.Driver");
                con=DriverManager.getConnection("jdbc:mysql://localhost/e_hospital_management","root","sukanyaSK@27");
                pst=con.prepareStatement("SELECT * FROM staff WHERE staff_id=? and staff_password=?");
                pst2=con.prepareStatement("SELECT * FROM patient WHERE pt_id=? and pt_password=?");
                pst.setInt(1, uid);
                pst.setString(2, password);
                pst2.setInt(1, uid);
                pst2.setString(2, password);
                rs=pst.executeQuery();
                rs2=pst2.executeQuery();
                
                if(txtType.getSelectedIndex()==1)
                {
                    if(rs.next())
                    {
                        String s_code=rs.getString(1);
                        int s_id=rs.getInt(2);
                        String s_name=rs.getString(3);
                        int s_year=rs.getInt(4);
                        String s_email=rs.getString(5);
                        String s_addr=rs.getString(6);
                        String s_password=rs.getString(7);
                        int s_salary=rs.getInt(8);
                
                        
                        pst3=con.prepareStatement("INSERT INTO staff_login_activity(staff_code, staff_id, staff_name, year_of_joining, staff_email, staff_address, staff_password, date_login, time_login, salary) VALUES(?,?,?,?,?,?,?,?,?,?)");
                        pst3.setString(1, s_code);
                        pst3.setInt(2, s_id);
                        pst3.setString(3, s_name);
                        pst3.setInt(4, s_year);
                        pst3.setString(5, s_email);
                        pst3.setString(6, s_addr);
                        pst3.setString(7, s_password);
                        pst3.setDate(8, java.sql.Date.valueOf(java.time.LocalDate.now()));
                        pst3.setTime(9, java.sql.Time.valueOf(java.time.LocalTime.now()));
                        pst3.setInt(10, s_salary);
                        pst3.executeUpdate();
                        
                        Staff st = new Staff();
                        this.hide();
                        st.setVisible(true);
                        
                        
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(this, "Invalid username or password");
                    }
                }
                else if(txtType.getSelectedIndex()==2)
                {
                    if(rs.next())
                    {
                        String s_code=rs.getString(1);
                        int s_id=rs.getInt(2);
                        String s_name=rs.getString(3);
                        int s_year=rs.getInt(4);
                        String s_email=rs.getString(5);
                        String s_addr=rs.getString(6);
                        String s_password=rs.getString(7);
                        int s_salary=rs.getInt(8);
                
                        
                        pst3=con.prepareStatement("INSERT INTO staff_login_activity(staff_code, staff_id, staff_name, year_of_joining, staff_email, staff_address, staff_password, date_login, time_login, salary) VALUES(?,?,?,?,?,?,?,?,?,?)");
                        pst3.setString(1, s_code);
                        pst3.setInt(2, s_id);
                        pst3.setString(3, s_name);
                        pst3.setInt(4, s_year);
                        pst3.setString(5, s_email);
                        pst3.setString(6, s_addr);
                        pst3.setString(7, s_password);
                        pst3.setDate(8, java.sql.Date.valueOf(java.time.LocalDate.now()));
                        pst3.setTime(9, java.sql.Time.valueOf(java.time.LocalTime.now()));
                        pst3.setInt(10, s_salary);
                        pst3.executeUpdate();

                        
                        Doctor d = new Doctor();
                        this.hide();
                        d.setVisible(true);
                        
                                            }
                    else
                    {
                        JOptionPane.showMessageDialog(this, "Invalid username or password");
                    }
                }
                else if(txtType.getSelectedIndex()==3)
                {
                    if(rs2.next())
                    {
                        
                        int p_id=rs2.getInt(1);
                        String p_name=rs2.getString(2);
                        String p_addr=rs2.getString(3);
                        int p_age=rs2.getInt(4);
                        String p_gender=rs2.getString(5);
                        String p_password=rs2.getString(7);
                        
                        pst3=con.prepareStatement("INSERT INTO patient_login_activity(pt_id, pt_name, pt_address, pt_age, pt_gender, date_of_login, time_of_login, pt_password) VALUES(?,?,?,?,?,?,?,?)");
                        pst3.setInt(1, p_id);
                        pst3.setString(2, p_name);
                        pst3.setString(3, p_addr);
                        pst3.setInt(4, p_age);
                        pst3.setString(5, p_gender);
                        pst3.setDate(6, java.sql.Date.valueOf(java.time.LocalDate.now()));
                        pst3.setTime(7, java.sql.Time.valueOf(java.time.LocalTime.now()));
                        pst3.setString(8, p_password);
                        pst3.executeUpdate();
                        
                        Patient pt = new Patient();
                        this.hide();
                        pt.setVisible(true);
                        
                        
                        
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(this, "Invalid username or password");
                    }
                }
                else if(txtType.getSelectedIndex()==4)
                {
                    if(rs.next())
                    {
                        String s_code=rs.getString(1);
                        int s_id=rs.getInt(2);
                        String s_name=rs.getString(3);
                        int s_year=rs.getInt(4);
                        String s_email=rs.getString(5);
                        String s_addr=rs.getString(6);
                        String s_password=rs.getString(7);
                        int s_salary=rs.getInt(8);
                
                        pst3=con.prepareStatement("INSERT INTO staff_login_activity(staff_code, staff_id, staff_name, year_of_joining, staff_email, staff_address, staff_password, date_login, time_login, salary) VALUES(?,?,?,?,?,?,?,?,?,?)");
                        pst3.setString(1, s_code);
                        pst3.setInt(2, s_id);
                        pst3.setString(3, s_name);
                        pst3.setInt(4, s_year);
                        pst3.setString(5, s_email);
                        pst3.setString(6, s_addr);
                        pst3.setString(7, s_password);
                        pst3.setDate(8, java.sql.Date.valueOf(java.time.LocalDate.now()));
                        pst3.setTime(9, java.sql.Time.valueOf(java.time.LocalTime.now()));
                        pst3.setInt(10, s_salary);
                        pst3.executeUpdate();
                        
                        Admin ad = new Admin();
                        this.hide();
                        ad.setVisible(true);
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(this, "Invalid Credentials");
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Invalid Credentials");
                }
                
 
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    
            
       
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        PatientRegisteration prg = new PatientRegisteration();
        this.hide();
        prg.setVisible(true);
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JComboBox<String> txtType;
    private javax.swing.JTextField txtUserId;
    // End of variables declaration//GEN-END:variables
}
